services:
    marble.entity_manager.entity_manager:
        class: Marble\EntityManager\EntityManager
        arguments:
            $ioProvider: '@Marble\EntityManager\Contract\EntityIoProvider'
            $dispatcher: '@?Psr\EventDispatcher\EventDispatcherInterface'
        public: true

    Marble\EntityManager\EntityManager: '@marble.entity_manager.entity_manager'

    marble.entity_manager.io_provider:
        class: Marble\EntityManager\Bundle\DefaultEntityIoProvider
        arguments:
            $readers: !tagged_locator
                tag: 'marble.entity_manager.entity_reader'
                default_index_method: 'getEntityClassName'
            $writers: '@marble.entity_manager.entity_writer_locator'
            $repositories: '@marble.entity_manager.custom_repository_locator'
        public: false

    Marble\EntityManager\Bundle\DefaultEntityIoProvider: '@marble.entity_manager.io_provider'
    Marble\EntityManager\Contract\EntityIoProvider: '@marble.entity_manager.io_provider'
